function [varargout] = VariationPointMass(varargin)
%% 
% This function was generated by the Scala: Dynamics on Manifold package
% Wed Jun 24 01:27:49 PDT 2020
% 
% NOTE: This function makes use of geometric-toolbox
% 		 link: https://github.com/HybridRobotics/geometric-toolbox
%%


%% Function Inputs
params = varargin{1};

%% 
A=-[zeros(3,3),zeros(3,3),;
];
B=-[((-1.0))*(eye(3)),;
];


%% Outputs
varargout{1} =A;
varargout{1} =B;

end